version: "3.9"

services:
  3s:
    build: .
    image: 3s:latest
    container_name: 3s
    entrypoint: ["/usr/local/bin/3s"]
    volumes:
      - 3s-config:/home/3s/.config/3s
      - 3s-cache:/home/3s/.cache/3s
    stdin_open: true
    tty: true
    security_opt:
      - seccomp:unconfined
    shm_size: "2gb"

volumes:
  3s-config:
  3s-cache:
